#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
#ifndef GINIBANKSDK_SWIFT_H
#define GINIBANKSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wduplicate-method-match"
#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT noexcept
#endif
#else
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT 
#endif
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_CXX_INT_DEFINED)
#define SWIFT_CXX_INT_DEFINED
namespace swift {
using Int = ptrdiff_t;
using UInt = size_t;
}
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import GiniCaptureSDK;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="GiniBankSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
@class NSBundle;
@class NSCoder;

/// This class is a view controller that lets the user view their invoice
/// together with the line items and total amount to pay. It will push the
/// <code>LineItemDetailsViewController</code> onto the navigation stack when the user
/// taps the “Edit” button on any of the line items.
SWIFT_CLASS("_TtC11GiniBankSDK28DigitalInvoiceViewController")
@interface DigitalInvoiceViewController : UIViewController
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end







@class UITableView;
@class NSIndexPath;
@class UITableViewCell;

@interface DigitalInvoiceViewController (SWIFT_EXTENSION(GiniBankSDK)) <UITableViewDataSource, UITableViewDelegate>
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView estimatedHeightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end

@protocol GiniCaptureDelegate;
@protocol GiniCaptureDocument;
@class GiniBankConfiguration;

/// Core class for Gini Bank SDK.
SWIFT_CLASS("_TtC11GiniBankSDK8GiniBank")
@interface GiniBank : NSObject
/// Returns a view controller which will handle the analysis process.
/// note:
/// Screen API only.
/// \param delegate An instance conforming to the <code>GiniCaptureDelegate</code> protocol.
///
/// \param importedDocuments Documents that come from a source different than <code>CameraViewController</code>.
/// There should be either images or one PDF, and they should be validated before calling this method.
///
///
/// returns:
/// A presentable view controller.
+ (UIViewController * _Nonnull)viewControllerWithDelegate:(id <GiniCaptureDelegate> _Nonnull)delegate importedDocuments:(NSArray<id <GiniCaptureDocument>> * _Nullable)importedDocuments SWIFT_WARN_UNUSED_RESULT;
/// Returns a view controller which will handle the analysis process.
/// note:
/// Screen API only.
/// \param delegate An instance conforming to the <code>GiniCaptureDelegate</code> protocol.
///
/// \param importedDocument Documents that come from a source different than CameraViewController.
/// There should be either images or one PDF, and they should be validated before calling this method.
///
///
/// returns:
/// A presentable view controller.
+ (UIViewController * _Nonnull)viewControllerWithDelegate:(id <GiniCaptureDelegate> _Nonnull)delegate importedDocument:(id <GiniCaptureDocument> _Nullable)importedDocument SWIFT_WARN_UNUSED_RESULT;
/// Returns a view controller which will handle the analysis process.
/// Allows to set a custom configuration to change the look and feel of the  Gini Bank SDK.
/// note:
/// Screen API only.
/// \param delegate An instance conforming to the <code>GiniCaptureDelegate</code> protocol.
///
/// \param configuration The bank configuration to set.
///
/// \param importedDocument Documents that come from a source different than CameraViewController.
/// There should be either images or one PDF, and they should be validated before calling this method.
///
///
/// returns:
/// A presentable view controller.
+ (UIViewController * _Nonnull)viewControllerWithDelegate:(id <GiniCaptureDelegate> _Nonnull)delegate withConfiguration:(GiniBankConfiguration * _Nonnull)configuration importedDocument:(id <GiniCaptureDocument> _Nullable)importedDocument SWIFT_WARN_UNUSED_RESULT;
/// Sets a configuration which is used to customize the look and feel of the Gini Bank SDK,
/// for example to change texts and colors displayed to the user.
/// \param configuration The bank configuration to set.
///
+ (void)setConfiguration:(GiniBankConfiguration * _Nonnull)configuration;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@class CustomDocumentValidationResult;
@protocol GiniLogger;
@class UIColor;
@class UIFont;
@class GiniColor;
@class UIView;
@protocol PreferredButtonResource;
@class GiniCaptureFont;

SWIFT_CLASS("_TtC11GiniBankSDK21GiniBankConfiguration")
@interface GiniBankConfiguration : NSObject
/// Indicates whether the Return Assistant feature is enabled or not. In case of <code>true</code>,
/// the user will be presented with a digital representation of their invoice where they
/// can see individual line items and are able to amend them or choose to not to pay for them.
@property (nonatomic) BOOL returnAssistantEnabled;
/// Returns a <code>GiniBankConfiguration</code> instance which allows to set individual configurations
/// to change the look and feel of the Gini Bank SDK.
///
/// returns:
/// Instance of <code>GiniBankConfiguration</code>.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Sets custom validations that can be done apart from the default ones (file size, file type…).
/// It should throw a <code>CustomDocumentValidationError</code> error.
@property (nonatomic, copy) CustomDocumentValidationResult * _Nonnull (^ _Nonnull customDocumentValidations)(id <GiniCaptureDocument> _Nonnull);
/// Can be turned on during development to unlock extra information and to save captured images to camera roll.
/// warning:
/// Should never be used outside of a development enviroment.
@property (nonatomic) BOOL debugModeOn;
/// Used to handle all the logging messages in order to log them in a different way.
@property (nonatomic, strong) id <GiniLogger> _Nonnull logger;
/// Indicates whether the multipage feature is enabled or not. In case of <code>true</code>,
/// multiple pages can be processed, showing a different review screen when capturing.
@property (nonatomic) BOOL multipageEnabled;
/// Sets the tint color of the navigation bar in all screens of the Gini Bank SDK to
/// the globally specified color or to a default color.
/// note:
/// Screen API only.
@property (nonatomic, strong) UIColor * _Nonnull navigationBarTintColor;
/// Sets the tint color of all navigation items in all screens of the Gini Bank SDK to
/// the globally specified color.
/// note:
/// Screen API only.
@property (nonatomic, strong) UIColor * _Nullable navigationBarItemTintColor;
/// Sets the font of all navigation items in all screens of the Gini Bank SDK to
/// the globally specified font or a default font.
/// note:
/// Screen API only.
@property (nonatomic, strong) UIFont * _Nonnull navigationBarItemFont;
/// Sets the title color in the navigation bar in all screens of the Gini Bank SDK to
/// the globally specified color or to a default color.
/// note:
/// Screen API only.
@property (nonatomic, strong) UIColor * _Nonnull navigationBarTitleColor;
/// Sets the title font in the navigation bar in all screens of the Gini Bank SDK to
/// the globally specified font or to a default font.
/// note:
/// Screen API only.
@property (nonatomic, strong) UIFont * _Nonnull navigationBarTitleFont;
/// Sets the tint color of the UIDocumentPickerViewController navigation bar.
/// note:
/// Use only if you have a custom <code>UIAppearance</code> for your UINavigationBar
/// note:
/// Only iOS >= 11.0
@property (nonatomic, strong) UIColor * _Nullable documentPickerNavigationBarTintColor;
/// Sets the background color of an informal notice. Notices are small pieces of
/// information appearing underneath the navigation bar.
@property (nonatomic, strong) UIColor * _Nonnull noticeInformationBackgroundColor;
/// Sets the text color of an informal notice. Notices are small pieces of
/// information appearing underneath the navigation bar.
@property (nonatomic, strong) UIColor * _Nonnull noticeInformationTextColor;
/// Sets the background color of an error notice. Notices are small pieces of
/// information appearing underneath the navigation bar.
@property (nonatomic, strong) UIColor * _Nonnull noticeErrorBackgroundColor;
/// Sets the text color of an error notice. Notices are small pieces of
/// information appearing underneath the navigation bar.
@property (nonatomic, strong) UIColor * _Nonnull noticeErrorTextColor;
/// Indicates whether the open with feature is enabled or not. In case of <code>true</code>,
/// a new option with the open with tutorial wil be shown in the Help menu.
@property (nonatomic) BOOL openWithEnabled;
/// Indicates whether the QR Code scanning feature is enabled or not.
@property (nonatomic) BOOL qrCodeScanningEnabled;
/// Indicates the status bar style in the Gini Bank SDK.
/// note:
/// If <code>UIViewControllerBasedStatusBarAppearance</code> is set to <code>false</code> in the <code>Info.plist</code>,
/// it may not work in future versions of iOS since the <code>UIApplication.setStatusBarStyle</code> method was
/// deprecated on iOS 9.0.
@property (nonatomic) UIStatusBarStyle statusBarStyle;
/// Sets the text color of the descriptional text when camera access was denied.
@property (nonatomic, strong) UIColor * _Nonnull cameraNotAuthorizedTextColor;
/// Sets the text color of the button title when camera access was denied.
@property (nonatomic, strong) UIColor * _Nonnull cameraNotAuthorizedButtonTitleColor;
/// Sets the color of camera preview corner guides.
@property (nonatomic, strong) UIColor * _Nonnull cameraPreviewCornerGuidesColor;
/// Sets the background color of camera container view.
@property (nonatomic, strong) GiniColor * _Nonnull cameraContainerViewBackgroundColor;
/// Sets the color of camera preview frame.
@property (nonatomic, strong) GiniColor * _Nonnull cameraPreviewFrameColor;
/// Sets the background color of camera buttons view.
@property (nonatomic, strong) GiniColor * _Nonnull cameraButtonsViewBackgroundColor;
/// Set the types supported by the file import feature. <code>GiniCaptureImportFileTypes.none</code> by default.
@property (nonatomic) enum GiniCaptureImportFileTypes fileImportSupportedTypes;
/// Sets the background color of the new file import button hint.
@property (nonatomic, strong) UIColor * _Nonnull fileImportToolTipBackgroundColor;
/// Sets the text color of the new file import button hint.
@property (nonatomic, strong) UIColor * _Nonnull fileImportToolTipTextColor;
/// Sets the close button color of the new file import button hint.
@property (nonatomic, strong) UIColor * _Nonnull fileImportToolTipCloseButtonColor;
/// Sets the text color of the item selected background check.
@property (nonatomic, strong) UIColor * _Nonnull galleryPickerItemSelectedBackgroundCheckColor;
/// Sets the background color for gallery screen.
@property (nonatomic, strong) GiniColor * _Nonnull galleryScreenBackgroundColor;
/// Indicates whether the flash toggle should be shown in the camera screen.
@property (nonatomic) BOOL flashToggleEnabled;
/// When the flash toggle is enabled, this flag indicates if the flash is on by default.
@property (nonatomic) BOOL flashOnByDefault;
/// Sets the color of the captured images stack indicator label
@property (nonatomic, strong) UIColor * _Nonnull imagesStackIndicatorLabelTextcolor;
/// Sets the close button text in the navigation bar on the camera screen.
/// note:
/// Screen API only.
@property (nonatomic, copy) NSString * _Nonnull navigationBarCameraTitleCloseButton;
/// Sets the help button text in the navigation bar on the camera screen.
/// note:
/// Screen API only.
@property (nonatomic, copy) NSString * _Nonnull navigationBarCameraTitleHelpButton;
/// Sets the text color of the QR Code popup button.
@property (nonatomic, strong) UIColor * _Nonnull qrCodePopupButtonColor;
/// Sets the text color of the QR Code popup label.
@property (nonatomic, strong) GiniColor * _Nonnull qrCodePopupTextColor;
/// Sets the text color of the QR Code popup background.
@property (nonatomic, strong) GiniColor * _Nonnull qrCodePopupBackgroundColor;
/// Sets the continue button text in the navigation bar on the onboarding screen.
/// note:
/// Screen API only.
@property (nonatomic, copy) NSString * _Nonnull navigationBarOnboardingTitleContinueButton;
/// Sets the color of the page controller’s page indicator items.
@property (nonatomic, strong) GiniColor * _Nonnull onboardingPageIndicatorColor;
/// Sets the color of the page controller’s current page indicator item.
@property (nonatomic, strong) GiniColor * _Nonnull onboardingCurrentPageIndicatorColor;
/// Sets alpha to the color of the page controller’s current page indicator item.
@property (nonatomic) CGFloat onboardingCurrentPageIndicatorAlpha;
/// Indicates whether the onboarding screen should be presented at each start of the Gini Bank SDK.
/// note:
/// Screen API only.
@property (nonatomic) BOOL onboardingShowAtLaunch;
/// Indicates whether the onboarding screen should be presented at the first
/// start of the Gini Bank SDK. It is advised to do so.
/// note:
/// Overwrites <code>onboardingShowAtLaunch</code> for the first launch.
/// note:
/// Screen API only.
@property (nonatomic) BOOL onboardingShowAtFirstLaunch;
/// Sets the color ot the text for all onboarding pages.
@property (nonatomic, strong) GiniColor * _Nonnull onboardingTextColor;
/// Sets the background color for all onboarding pages.
@property (nonatomic, strong) GiniColor * _Nonnull onboardingScreenBackgroundColor;
/// All onboarding pages which will be presented in a horizontal scroll view to the user.
/// By default the Gini Bank SDK comes with three pages advising the user to keep the
/// document flat, hold the device parallel and capture the whole document.
/// note:
/// Any array of views can be passed, but for your convenience we provide the <code>GINIOnboardingPage</code> class.
@property (nonatomic, copy) NSArray<UIView *> * _Nonnull onboardingPages;
/// Sets the back button text in the navigation bar on the review screen. Use this if you only want to show the title.
/// note:
/// Screen API only.
@property (nonatomic, copy) NSString * _Nonnull navigationBarReviewTitleBackButton;
/// Sets the close button text in the navigation bar on the review screen. Use this if you only want to show the title.
/// note:
/// Screen API only.
@property (nonatomic, copy) NSString * _Nonnull navigationBarReviewTitleCloseButton;
/// Sets the continue button text in the navigation bar on the review screen.
/// note:
/// Screen API only.
@property (nonatomic, copy) NSString * _Nonnull navigationBarReviewTitleContinueButton;
/// Sets the background color of the bottom section on the review screen containing the rotation button.
/// note:
/// Background will have a 20% transparency, to have enough space for the document image on smaller devices.
@property (nonatomic, strong) UIColor * _Nonnull reviewBottomViewBackgroundColor;
/// Sets the font of the text appearing at the bottom of the review screen.
@property (nonatomic, strong) UIFont * _Nonnull reviewTextBottomFont;
/// Sets the color of the text appearing at the bottom of the review screen.
@property (nonatomic, strong) UIColor * _Nonnull reviewTextBottomColor;
/// Sets the color of the pages container and toolbar.
@property (nonatomic, strong) GiniColor * _Nonnull multipagePagesContainerAndToolBarColor;
/// Sets the color of the circle indicator.
@property (nonatomic, strong) GiniColor * _Nonnull indicatorCircleColor;
/// Sets the tint color of the toolbar items.
@property (nonatomic, strong) UIColor * _Nonnull multipageToolbarItemsColor;
/// Sets the tint color of the page indicator.
@property (nonatomic, strong) UIColor * _Nonnull multipagePageIndicatorColor;
/// Sets the background color of the page selected indicator.
@property (nonatomic, strong) UIColor * _Nonnull multipagePageSelectedIndicatorColor;
/// Sets the background color of the page background.
@property (nonatomic, strong) GiniColor * _Nonnull multipagePageBackgroundColor;
/// Sets the tint color of the draggable icon in the page collection cell.
@property (nonatomic, strong) UIColor * _Nonnull multipageDraggableIconColor;
/// Sets the color of the loading indicator on the analysis screen to the specified color.
@property (nonatomic, strong) UIColor * _Nonnull analysisLoadingIndicatorColor;
/// Sets the color of the PDF information view on the analysis screen to the specified color.
@property (nonatomic, strong) UIColor * _Nonnull analysisPDFInformationBackgroundColor;
/// Sets the color of the PDF information view on the analysis screen to the specified color.
@property (nonatomic, strong) UIColor * _Nonnull analysisPDFInformationTextColor;
/// Sets the back button text in the navigation bar on the analysis screen. Use this if you only want to show the title.
/// note:
/// Screen API only.
@property (nonatomic, copy) NSString * _Nonnull navigationBarAnalysisTitleBackButton;
/// Sets the background color for all help screens.
@property (nonatomic, strong) GiniColor * _Nonnull helpScreenBackgroundColor;
/// Sets the background color for the cells on help screen.
@property (nonatomic, strong) GiniColor * _Nonnull helpScreenCellsBackgroundColor;
/// Sets the back button text in the navigation bar on the help menu screen. Use this if you only want to show the title.
/// note:
/// Screen API only.
@property (nonatomic, copy) NSString * _Nonnull navigationBarHelpMenuTitleBackToCameraButton;
/// Sets the back button text in the navigation bar on the help screen. Use this if you only want to show the title.
/// note:
/// Screen API only.
@property (nonatomic, copy) NSString * _Nonnull navigationBarHelpScreenTitleBackToMenuButton;
/// Indicates whether the supported format screens should be shown. In case of <code>false</code>,
/// the option won’t be shown in the Help menu.
@property (nonatomic) BOOL shouldShowSupportedFormatsScreen;
/// Sets the color of the unsupported formats icon background to the specified color.
@property (nonatomic, strong) UIColor * _Nonnull nonSupportedFormatsIconColor;
/// Sets the color of the supported formats icon background to the specified color.
@property (nonatomic, strong) UIColor * _Nonnull supportedFormatsIconColor;
/// Sets the text of the app name for the Open with tutorial texts.
@property (nonatomic, copy) NSString * _Nonnull openWithAppNameForTexts;
/// Sets the color of the step indicator for the Open with tutorial.
@property (nonatomic, strong) UIColor * _Nonnull stepIndicatorColor;
/// Sets the color of the bottom button to the specified color.
@property (nonatomic, strong) UIColor * _Nonnull noResultsBottomButtonColor;
/// Sets the text color of the bottom button to the specified color.
@property (nonatomic, strong) GiniColor * _Nonnull noResultsBottomButtonTextColor;
/// Sets the corner radius of the bottom button.
@property (nonatomic) CGFloat noResultsBottomButtonCornerRadius;
/// Sets the color of the warning container background to the specified color.
@property (nonatomic, strong) UIColor * _Nonnull noResultsWarningContainerIconColor;
/// Sets the text color for the select more photos button on the albums screen.
@property (nonatomic, strong) GiniColor * _Nonnull albumsScreenSelectMorePhotosTextColor;
/// Sets if the Drag&Drop step should be shown in the “Open with” tutorial.
@property (nonatomic) BOOL shouldShowDragAndDropTutorial;
@property (nonatomic, strong) id <PreferredButtonResource> _Nullable closeButtonResource;
@property (nonatomic, strong) id <PreferredButtonResource> _Nullable helpButtonResource;
@property (nonatomic, strong) id <PreferredButtonResource> _Nullable backToCameraButtonResource;
@property (nonatomic, strong) id <PreferredButtonResource> _Nullable backToMenuButtonResource;
@property (nonatomic, strong) id <PreferredButtonResource> _Nullable nextButtonResource;
@property (nonatomic, strong) id <PreferredButtonResource> _Nullable cancelButtonResource;
/// Sets the background color for the return assistant help screen.
@property (nonatomic, strong) GiniColor * _Nonnull helpReturnAssistantScreenBackgroundColor;
/// Sets the text color for the section titles on the return assistant help screen.
@property (nonatomic, strong) GiniColor * _Nonnull helpReturnAssistantScreenSectionTitleColor;
/// Sets the font for the page title on the return assistant help screen.
@property (nonatomic, strong) UIFont * _Nonnull helpReturnAssistantScreenPageTitleFont;
/// Sets the font for the section titles on the return assistant help screen.
@property (nonatomic, strong) UIFont * _Nonnull helpReturnAssistantScreenSectionTitleFont;
/// Sets the text color for the instructions on the return assistant help screen.
@property (nonatomic, strong) GiniColor * _Nonnull helpReturnAssistantScreenInstructionColor;
/// Sets the font for the instructions on the return assistant help screen.
@property (nonatomic, strong) UIFont * _Nonnull helpReturnAssistantScreenInstructionFont;
/// Sets the background color for the back button on the return assistant help screen.
@property (nonatomic, strong) UIColor * _Nonnull helpReturnAssistantScreenBackButtonColor;
/// Sets the title color for the back button on the return assistant help screen.
@property (nonatomic, strong) GiniColor * _Nonnull helpReturnAssistantScreenBackButtonTitleColor;
/// Sets the font for the back button title on the return assistant help screen.
@property (nonatomic, strong) UIFont * _Nonnull helpReturnAssistantScreenBackButtonTitleFont;
/// Sets the color of the active elements on the digital invoice line item cells to the specified color.
/// Can be overridden by the specific line item tint color customisation options: <code>lineItemBorderColor</code>, <code>digitalInvoiceLineItemEditButtonTintColor</code>,
/// <code>digitalInvoiceLineItemToggleSwitchTintColor</code>, <code>digitalInvoiceLineItemDeleteButtonTintColor</code>.
@property (nonatomic, strong) UIColor * _Nonnull lineItemTintColor;
/// Sets the border color on the digital invoice line item cells to the specified color.
/// Overrides <code>lineItemTintColor</code> if not <code>nil</code>.
@property (nonatomic, strong) UIColor * _Nullable lineItemBorderColor;
/// Sets the color of the active elements on the digital invoice line item count label to the specified color.
@property (nonatomic, strong) UIColor * _Nonnull lineItemCountLabelColor;
/// Sets the font of the line item name on the digital invoice  line item count label to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull lineItemCountLabelFont;
/// Sets the font of the line item name on the digital invoice screen to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceLineItemNameFont;
/// Sets the font of the line item edit button title on the digital invoice screen to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceLineItemEditButtonTitleFont;
/// Sets the edit button tint color on the digital invoice screen to the specified color.
/// Overrides <code>lineItemTintColor</code> if not <code>nil</code>.
@property (nonatomic, strong) UIColor * _Nullable digitalInvoiceLineItemEditButtonTintColor;
/// Sets the toggle switch tint color on the digital invoice line item cells to the specified color.
/// Overrides <code>lineItemTintColor</code> if not <code>nil</code>.
@property (nonatomic, strong) UIColor * _Nullable digitalInvoiceLineItemToggleSwitchTintColor;
/// Sets the delete button tint color on the digital invoice screen to the specified color.
/// Overrides <code>lineItemTintColor</code> if not <code>nil</code>.
@property (nonatomic, strong) UIColor * _Nullable digitalInvoiceLineItemDeleteButtonTintColor;
/// Sets the font of the line item label that displays the quantity on the digital invoice screen to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceLineItemQuantityFont;
/// Sets the color of  the line item label that  displays the quantity on the digital invoice line item cells to the specified color.
@property (nonatomic, strong) GiniColor * _Nonnull digitalInvoiceLineItemQuantityColor;
/// Sets the color of  the line item label that displays the item name on the digital invoice line item cells to the specified color.
@property (nonatomic, strong) GiniColor * _Nonnull digitalInvoiceLineItemNameColor;
/// Sets the color of  the line item label that displays the price on the digital invoice line item cells to the specified color.
@property (nonatomic, strong) GiniColor * _Nonnull digitalInvoiceLineItemPriceColor;
/// Sets the font of the main currency unit of the price on the line item of the digital invoice screen to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceLineItemPriceMainUnitFont;
/// Sets the font of the fractional currency unit of the price on the line item of the digital invoice screen to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceLineItemPriceFractionalUnitFont;
/// Sets the font of the secondary informational message on the digital invoice screen to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceSecondaryMessageTextFont;
/// Sets the color of the secondary message label on the digital invoice line item cells to the specified color.
@property (nonatomic, strong) UIColor * _Nonnull digitalInvoiceSecondaryMessageTextColor;
/// Sets the background color for digital invoice screen.
@property (nonatomic, strong) GiniColor * _Nonnull digitalInvoiceBackgroundColor;
/// Sets the background color for the line items on the digital invoice screen.
@property (nonatomic, strong) GiniColor * _Nonnull digitalInvoiceLineItemsBackgroundColor;
/// Sets the disabled color for the line items on the digital invoice screen.
@property (nonatomic, strong) UIColor * _Nonnull digitalInvoiceLineItemsDisabledColor;
/// Sets the font of the footer message on the digital invoice screen to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceFooterMessageTextFont;
/// Sets the add article button tint color of the footer section on the digital invoice screen.
@property (nonatomic, strong) UIColor * _Nonnull digitalInvoiceFooterAddArticleButtonTintColor;
/// Sets the font of the add article button of the footer section on the digital invoice screen.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceFooterAddArticleButtonTitleFont;
/// Sets the text color of the footer message on the digital invoice screen.
@property (nonatomic, strong) GiniColor * _Nonnull digitalInvoiceFooterMessageTextColor;
/// Sets the text color of the items section header on the digital invoice screen.
@property (nonatomic, strong) GiniColor * _Nonnull digitalInvoiceItemsSectionHeaderTextColor;
/// Sets the font of the items section header on the digital invoice screen to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceItemsSectionHeaderTextFont;
/// Sets the background color of the digital invoice pay button to the specified color.
@property (nonatomic, strong) UIColor * _Nonnull payButtonBackgroundColor;
/// Sets the title text color of the digital invoice pay button to the specified color.
@property (nonatomic, strong) UIColor * _Nonnull payButtonTitleTextColor;
/// Sets the title text font of the digital invoice pay button to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull payButtonTitleFont;
/// Sets the background color of the digital invoice skip button to the specified color.
@property (nonatomic, strong) UIColor * _Nonnull skipButtonBackgroundColor;
/// Sets the title text color of the digital invoice skip button to the specified color.
@property (nonatomic, strong) UIColor * _Nonnull skipButtonTitleTextColor;
/// Sets the layer border color of the digital invoice skip button to the specified color.
@property (nonatomic, strong) UIColor * _Nonnull skipButtonBorderColor;
/// Sets the title text font of the digital invoice skip button to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull skipButtonTitleFont;
/// Sets the font of the addon labels on the digital invoice screen to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceAddonLabelFont;
/// Sets the font of the total caption label on the digital invoice screen to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceTotalCaptionLabelFont;
/// Sets the text color of the total caption label on the digital invoice screen.
@property (nonatomic, strong) GiniColor * _Nonnull digitalInvoiceTotalCaptionLabelTextColor;
/// Sets the font of the total explanation label on the digital invoice screen to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceTotalExplanationLabelFont;
/// Sets the text color of the explanation label on the digital invoice screen.
@property (nonatomic, strong) GiniColor * _Nonnull digitalInvoiceTotalExplanationLabelTextColor;
/// Sets the font of the main unit of the addon price labels to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceAddonPriceMainUnitFont;
/// Sets the font of the fractional unit of the addon price labels to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceAddonPriceFractionalUnitFont;
/// Sets the color of the addon price labels in the digital invoice screen to the specified color.
@property (nonatomic, strong) UIColor * _Nonnull digitalInvoiceAddonPriceColor;
/// Sets the color of the addon name labels in the digital invoice screen to the specified color
@property (nonatomic, strong) GiniColor * _Nonnull digitalInvoiceAddonLabelColor;
/// Sets the color of the total price label in the digital invoice screen to the specified color.
@property (nonatomic, strong) UIColor * _Nonnull digitalInvoiceTotalPriceColor;
/// Sets the font of the digital invoice main unit of the total price label to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceTotalPriceMainUnitFont;
/// Sets the font of the digital invoice fractional unit of the total price label to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceTotalPriceFractionalUnitFont;
/// Sets the font of the content description labels in the line item details view controller to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull lineItemDetailsDescriptionLabelFont;
/// Sets the color of the content description labels in the line item details view controller to the specified color.
@property (nonatomic, strong) UIColor * _Nonnull lineItemDetailsDescriptionLabelColor;
/// Sets the background color for  the line item details view.
@property (nonatomic, strong) GiniColor * _Nonnull lineItemDetailsBackgroundColor;
/// Sets the font of the content labels in the line item details view controller to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull lineItemDetailsContentLabelFont;
/// Sets the color of the content labels in the line item details view controller to the specified color.
@property (nonatomic, strong) UIColor * _Nonnull lineItemDetailsContentLabelColor;
/// Sets the highlighted underline color of the content labels in the line item details view controller to the specified color
@property (nonatomic, strong) UIColor * _Nonnull lineItemDetailsContentHighlightedColor;
/// Sets the font of the line item details screen main unit of the total price label to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull lineItemDetailsTotalPriceMainUnitFont;
/// Sets the font of the line item details screen fractional unit of the total price label to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull lineItemDetailsTotalPriceFractionalUnitFont;
/// Sets the backgroundColor on the digital invoice onboarding screen.
@property (nonatomic, strong) GiniColor * _Nonnull digitalInvoiceOnboardingBackgroundColor;
/// Sets the color on the digital invoice onboarding screen for text labels.
@property (nonatomic, strong) GiniColor * _Nonnull digitalInvoiceOnboardingTextColor;
/// Sets the font of the first text label on the digital invoice onboarding screen.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceOnboardingFirstLabelTextFont;
/// Sets the font of the second text label on the digital invoice onboarding screen.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceOnboardingSecondLabelTextFont;
/// Sets the backgroundColor  on the digital invoice onboarding screen for done button.
@property (nonatomic, strong) GiniColor * _Nonnull digitalInvoiceOnboardingDoneButtonBackgroundColor;
/// Sets the font of the done button on the digital invoice onboarding screen.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceOnboardingDoneButtonTextFont;
/// Sets the font of the hide button on the digital invoice onboarding screen.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceOnboardingHideButtonTextFont;
/// Sets the text color of the done button on the digital invoice onboarding screen.
@property (nonatomic, strong) GiniColor * _Nonnull digitalInvoiceOnboardingDoneButtonTextColor;
/// Sets the text color of the done button on the digital invoice onboarding screen.
@property (nonatomic, strong) GiniColor * _Nonnull digitalInvoiceOnboardingHideButtonTextColor;
/// Sets the background color of the warning info view on the digital invoice screen.
@property (nonatomic, strong) UIColor * _Nonnull digitalInvoiceInfoViewBackgroundColor;
/// Sets the  chevron image tint color of the warning info view on the digital invoice screen.
@property (nonatomic, strong) UIColor * _Nonnull digitalInvoiceInfoViewChevronImageViewTintColor;
/// Sets the text color for the warning info view warning labels on the digital invoice screen.
@property (nonatomic, strong) UIColor * _Nonnull digitalInvoiceInfoViewWarningLabelsTextColor;
/// Sets the font for the warning info view top label on the digital invoice screen.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceInfoViewTopLabelFont;
/// Sets the font for the warning info view middle label on the digital invoice screen.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceInfoViewMiddleLabelFont;
/// Sets the font for the warning info view bottom label on the digital invoice screen.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceInfoViewBottomLabelFont;
/// Sets the background color for the warning info left button on the digital invoice screen.
@property (nonatomic, strong) UIColor * _Nonnull digitalInvoiceInfoViewLeftButtonBackgroundColor;
/// Sets the border color for the warning info left button on the digital invoice screen.
@property (nonatomic, strong) UIColor * _Nonnull digitalInvoiceInfoViewLeftButtonBorderColor;
/// Sets the title color for the warning info left button on the digital invoice screen.
@property (nonatomic, strong) UIColor * _Nonnull digitalInvoiceInfoViewLeftkButtonTitleColor;
/// Sets the background color for the warning info right button on the digital invoice screen.
@property (nonatomic, strong) UIColor * _Nonnull digitalInvoiceInfoViewRightButtonBackgroundColor;
/// Sets the border color for the warning info right button on the digital invoice screen.
@property (nonatomic, strong) UIColor * _Nonnull digitalInvoiceInfoViewRightButtonBorderColor;
/// Sets the title color for the warning info right button on the digital invoice screen.
@property (nonatomic, strong) UIColor * _Nonnull digitalInvoiceInfoViewRightButtonTitleColor;
/// Sets the font for the warning info buttons on the digital invoice screen.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceInfoViewButtonsFont;
/// Shows the return reasons dialog.
@property (nonatomic) BOOL enableReturnReasons;
/// Sets the font used in the Return Assistant screens by default.
@property (nonatomic, strong) GiniCaptureFont * _Nonnull customFont;
@end


SWIFT_CLASS("_TtC11GiniBankSDK28ReturnAssistantConfiguration")
@interface ReturnAssistantConfiguration : NSObject
/// Returns a <code>ReturnAssistantConfiguration</code> instance which allows to set individual configurations
/// to change the look and feel of the Gini Capture SDK.
///
/// returns:
/// Instance of <code>ReturnAssistantConfiguration</code>.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Sets the background color for the return assistant help screen.
@property (nonatomic, strong) GiniColor * _Nonnull helpReturnAssistantScreenBackgroundColor;
/// Sets the text color for the section titles on the return assistant help screen.
@property (nonatomic, strong) GiniColor * _Nonnull helpReturnAssistantScreenSectionTitleColor;
/// Sets the font for the page title on the return assistant help screen.
@property (nonatomic, strong) UIFont * _Nonnull helpReturnAssistantScreenPageTitleFont;
/// Sets the font for the section titles on the return assistant help screen.
@property (nonatomic, strong) UIFont * _Nonnull helpReturnAssistantScreenSectionTitleFont;
/// Sets the text color for the instructions on the return assistant help screen.
@property (nonatomic, strong) GiniColor * _Nonnull helpReturnAssistantScreenInstructionColor;
/// Sets the font for the instructions on the return assistant help screen.
@property (nonatomic, strong) UIFont * _Nonnull helpReturnAssistantScreenInstructionFont;
/// Sets the background color for the back button on the return assistant help screen.
@property (nonatomic, strong) UIColor * _Nonnull helpReturnAssistantScreenBackButtonColor;
/// Sets the title color for the back button on the return assistant help screen.
@property (nonatomic, strong) GiniColor * _Nonnull helpReturnAssistantScreenBackButtonTitleColor;
/// Sets the font for the back button title on the return assistant help screen.
@property (nonatomic, strong) UIFont * _Nonnull helpReturnAssistantScreenBackButtonTitleFont;
/// Sets the color of the active elements on the digital invoice line item cells to the specified color.
/// Can be overridden by the specific line item tint color customisation options: <code>lineItemBorderColor</code>, <code>digitalInvoiceLineItemEditButtonTintColor</code>,
/// <code>digitalInvoiceLineItemToggleSwitchTintColor</code>, <code>digitalInvoiceLineItemDeleteButtonTintColor</code>.
@property (nonatomic, strong) UIColor * _Nonnull lineItemTintColor;
/// Sets the border color on the digital invoice line item cells to the specified color.
/// Overrides <code>lineItemTintColor</code> if not <code>nil</code>.
@property (nonatomic, strong) UIColor * _Nullable lineItemBorderColor;
/// Sets the color of the active elements on the digital invoice line item count label to the specified color
@property (nonatomic, strong) UIColor * _Nonnull lineItemCountLabelColor;
/// Sets the font of the line item name on the digital invoice  line item count label to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull lineItemCountLabelFont;
/// Sets the font of the line item name on the digital invoice screen to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceLineItemNameFont;
/// Sets the font of the line item edit button title on the digital invoice screen to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceLineItemEditButtonTitleFont;
/// Sets the edit button tint color on the digital invoice screen to the specified color.
/// Overrides <code>lineItemTintColor</code> if not <code>nil</code>.
@property (nonatomic, strong) UIColor * _Nullable digitalInvoiceLineItemEditButtonTintColor;
/// Sets the toggle switch tint color on the digital invoice line item cells to the specified color.
/// Overrides <code>lineItemTintColor</code> if not <code>nil</code>.
@property (nonatomic, strong) UIColor * _Nullable digitalInvoiceLineItemToggleSwitchTintColor;
/// Sets the delete button tint color on the digital invoice screen to the specified color.
/// Overrides <code>lineItemTintColor</code> if not <code>nil</code>.
@property (nonatomic, strong) UIColor * _Nullable digitalInvoiceLineItemDeleteButtonTintColor;
/// Sets the font of the line item label that displays the quantity on the digital invoice screen to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceLineItemQuantityFont;
/// Sets the color of  the line item label that displays the quantity on the digital invoice line item cells to the specified color.
@property (nonatomic, strong) GiniColor * _Nonnull digitalInvoiceLineItemQuantityColor;
/// Sets the color of  the line item label that displays the item name on the digital invoice line item cells to the specified color.
@property (nonatomic, strong) GiniColor * _Nonnull digitalInvoiceLineItemNameColor;
/// Sets the color of  the line item label that displays the price on the digital invoice line item cells to the specified color.
@property (nonatomic, strong) GiniColor * _Nonnull digitalInvoiceLineItemPriceColor;
/// Sets the font of the main currency unit of the price on the line item
/// of the digital invoice screen to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceLineItemPriceMainUnitFont;
/// Sets the font of the fractional currency unit of the price on the line item
/// of the digital invoice screen to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceLineItemPriceFractionalUnitFont;
/// Sets the font of the secondary informational message on the digital invoice screen to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceSecondaryMessageTextFont;
/// Sets the color of the secondary message label on the digital invoice line item cells to the specified color
@property (nonatomic, strong) UIColor * _Nonnull digitalInvoiceSecondaryMessageTextColor;
/// Sets the background color for digital invoice screen.
@property (nonatomic, strong) GiniColor * _Nonnull digitalInvoiceBackgroundColor;
/// Sets the background color for the line items on the digital invoice screen.
@property (nonatomic, strong) GiniColor * _Nonnull digitalInvoiceLineItemsBackgroundColor;
/// Sets the disabled color for the line items on the digital invoice screen.
@property (nonatomic, strong) UIColor * _Nonnull digitalInvoiceLineItemsDisabledColor;
/// Sets the font of the footer message on the digital invoice screen to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceFooterMessageTextFont;
/// Sets the add article button tint color of the footer section on the digital invoice screen.
@property (nonatomic, strong) UIColor * _Nonnull digitalInvoiceFooterAddArticleButtonTintColor;
/// Sets the font of the add article button of the footer section on the digital invoice screen.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceFooterAddArticleButtonTitleFont;
/// Sets the text color of the footer message on the digital invoice screen.
@property (nonatomic, strong) GiniColor * _Nonnull digitalInvoiceFooterMessageTextColor;
/// Sets the font of the items section header on the digital invoice screen to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceItemsSectionHeaderTextFont;
/// Sets the text color of the items section header on the digital invoice screen.
@property (nonatomic, strong) GiniColor * _Nonnull digitalInvoiceItemsSectionHeaderTextColor;
/// Sets the background color of the digital invoice pay button to the specified color
@property (nonatomic, strong) UIColor * _Nonnull payButtonBackgroundColor;
/// Sets the title text color of the digital invoice pay button to the specified color
@property (nonatomic, strong) UIColor * _Nonnull payButtonTitleTextColor;
/// Sets the title text font of the digital invoice pay button to the specified font
@property (nonatomic, strong) UIFont * _Nonnull payButtonTitleFont;
/// Sets the background color of the digital invoice skip button to the specified color
@property (nonatomic, strong) UIColor * _Nonnull skipButtonBackgroundColor;
/// Sets the title text color of the digital invoice skip button to the specified color
@property (nonatomic, strong) UIColor * _Nonnull skipButtonTitleTextColor;
/// Sets the layer border color of the digital invoice skip button to the specified color
@property (nonatomic, strong) UIColor * _Nonnull skipButtonBorderColor;
/// Sets the title text font of the digital invoice skip button to the specified font
@property (nonatomic, strong) UIFont * _Nonnull skipButtonTitleFont;
/// Sets the font of the addon labels on the digital invoice screen to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceAddonLabelFont;
/// Sets the font of the total caption label on the digital invoice screen to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceTotalCaptionLabelFont;
/// Sets the text color of the total caption label on the digital invoice screen.
@property (nonatomic, strong) GiniColor * _Nonnull digitalInvoiceTotalCaptionLabelTextColor;
/// Sets the font of the total explanation label on the digital invoice screen to the specified font.
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceTotalExplanationLabelFont;
/// Sets the text color of the explanation label on the digital invoice screen.
@property (nonatomic, strong) GiniColor * _Nonnull digitalInvoiceTotalExplanationLabelTextColor;
/// Sets the font of the main unit of the addon price labels to the specified font
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceAddonPriceMainUnitFont;
/// Sets the font of the fractional unit of the addon price labels to the specified font
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceAddonPriceFractionalUnitFont;
/// Sets the color of the addon price labels in the digital invoice screen to the specified color
@property (nonatomic, strong) UIColor * _Nonnull digitalInvoiceAddonPriceColor;
/// Sets the color of the addon name labels in the digital invoice screen to the specified color
@property (nonatomic, strong) GiniColor * _Nonnull digitalInvoiceAddonLabelColor;
/// Sets the color of the total price label in the digital invoice screen to the specified color
@property (nonatomic, strong) UIColor * _Nonnull digitalInvoiceTotalPriceColor;
/// Sets the font of the digital invoice main unit of the total price label to the specified font
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceTotalPriceMainUnitFont;
/// Sets the font of the digital invoice fractional unit of the total price label to the specified font
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceTotalPriceFractionalUnitFont;
/// Sets the font of the content description labels in the line item details view controller to the specified font
@property (nonatomic, strong) UIFont * _Nonnull lineItemDetailsDescriptionLabelFont;
/// Sets the color of the content description labels in the line item details view controller to the specified color
@property (nonatomic, strong) UIColor * _Nonnull lineItemDetailsDescriptionLabelColor;
/// Sets the background color for  the line item details view.
@property (nonatomic, strong) GiniColor * _Nonnull lineItemDetailsBackgroundColor;
/// Sets the font of the content labels in the line item details view controller to the specified font
@property (nonatomic, strong) UIFont * _Nonnull lineItemDetailsContentLabelFont;
/// Sets the color of the content labels in the line item details view controller to the specified color
@property (nonatomic, strong) UIColor * _Nonnull lineItemDetailsContentLabelColor;
/// Sets the highlighted color of the content labels in the line item details view controller to the specified color
@property (nonatomic, strong) UIColor * _Nonnull lineItemDetailsContentHighlightedColor;
/// Sets the font of the line item details screen main unit of the total price label to the specified font
@property (nonatomic, strong) UIFont * _Nonnull lineItemDetailsTotalPriceMainUnitFont;
/// Sets the font of the line item details screen fractional unit of the total price label to the specified font
@property (nonatomic, strong) UIFont * _Nonnull lineItemDetailsTotalPriceFractionalUnitFont;
/// Sets the backgroundColor on the digital invoice onboarding screen
@property (nonatomic, strong) GiniColor * _Nonnull digitalInvoiceOnboardingBackgroundColor;
/// Sets the color on the digital invoice onboarding screen for text labels
@property (nonatomic, strong) GiniColor * _Nonnull digitalInvoiceOnboardingTextColor;
/// Sets the font of the first text label on the digital invoice onboarding screen
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceOnboardingFirstLabelTextFont;
/// Sets the font of the second text label on the digital invoice onboarding screen
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceOnboardingSecondLabelTextFont;
/// Sets the backgroundColor  on the digital invoice onboarding screen for done button
@property (nonatomic, strong) GiniColor * _Nonnull digitalInvoiceOnboardingDoneButtonBackgroundColor;
/// Sets the font of the done button on the digital invoice onboarding screen
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceOnboardingDoneButtonTextFont;
/// Sets the font of the hide button on the digital invoice onboarding screen
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceOnboardingHideButtonTextFont;
/// Sets the text color of the done button on the digital invoice onboarding screen
@property (nonatomic, strong) GiniColor * _Nonnull digitalInvoiceOnboardingDoneButtonTextColor;
/// Sets the text color of the done button on the digital invoice onboarding screen
@property (nonatomic, strong) GiniColor * _Nonnull digitalInvoiceOnboardingHideButtonTextColor;
/// Sets the background color of the warning info view on the digital invoice screen
@property (nonatomic, strong) UIColor * _Nonnull digitalInvoiceInfoViewBackgroundColor;
/// Sets the  chevron image tint color of the warning info view on the digital invoice screen
@property (nonatomic, strong) UIColor * _Nonnull digitalInvoiceInfoViewChevronImageViewTintColor;
/// Sets the text color for the warning info view warning labels on the digital invoice screen
@property (nonatomic, strong) UIColor * _Nonnull digitalInvoiceInfoViewWarningLabelsTextColor;
/// Sets the font for the warning info view top label on the digital invoice screen
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceInfoViewTopLabelFont;
/// Sets the font for the warning info view middle label on the digital invoice screen
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceInfoViewMiddleLabelFont;
/// Sets the font for the warning info view bottom label on the digital invoice screen
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceInfoViewBottomLabelFont;
/// Sets the background color for the warning info left button on the digital invoice screen
@property (nonatomic, strong) UIColor * _Nonnull digitalInvoiceInfoViewLeftButtonBackgroundColor;
/// Sets the border color for the warning info left button on the digital invoice screen
@property (nonatomic, strong) UIColor * _Nonnull digitalInvoiceInfoViewLeftButtonBorderColor;
/// Sets the title color for the warning info left button on the digital invoice screen
@property (nonatomic, strong) UIColor * _Nonnull digitalInvoiceInfoViewLeftkButtonTitleColor;
/// Sets the background color for the warning info right button on the digital invoice screen
@property (nonatomic, strong) UIColor * _Nonnull digitalInvoiceInfoViewRightButtonBackgroundColor;
/// Sets the border color for the warning info right button on the digital invoice screen
@property (nonatomic, strong) UIColor * _Nonnull digitalInvoiceInfoViewRightButtonBorderColor;
/// Sets the title color for the warning info right button on the digital invoice screen
@property (nonatomic, strong) UIColor * _Nonnull digitalInvoiceInfoViewRightButtonTitleColor;
/// Sets the font for the warning info buttons on the digital invoice screen
@property (nonatomic, strong) UIFont * _Nonnull digitalInvoiceInfoViewButtonsFont;
/// Shows the return reasons dialog.
@property (nonatomic) BOOL enableReturnReasons;
/// Sets the font used in the Return Assistant screens by default.
@property (nonatomic, strong) GiniCaptureFont * _Nonnull customFont;
@end



#endif
#if defined(__cplusplus)
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
